## **Creando una lista de 10 elementoss**

In [15]:
import numpy as np

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## **Transformando de array** 

In [16]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el de tipo de estrucutra**

In [17]:
type(arreglo)


numpy.ndarray

## **Corroborando el tipo de datos de arreglo**

In [18]:
arreglo.dtype


dtype('int32')

## **Definiendo el Array de int32 a float32**

In [19]:
np.array(arreglo, dtype=np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32**

In [20]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando los datos de int32 a float32**

In [21]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)