## **Creando una lista de 10 elementoss**

In [86]:
import numpy as np

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## <h1 style = "color:green"><b> **Transformando de array**<h1>

In [87]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el de tipo de estrucutra**

In [88]:
type(arreglo)


numpy.ndarray

## **Corroborando el tipo de datos de arreglo**

In [89]:
arreglo.dtype


dtype('int32')

## **Definiendo el Array de int32 a float32**

In [90]:
np.array(arreglo, dtype=np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32**

In [91]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando los datos de int32 a float32**

In [92]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Obteniendo le promedio de array**

In [93]:
promedio = np.mean(arreglo)
promedio

5.5

## **Obteniendo mediana de array**

In [94]:
mediana = np.median(arreglo)
mediana

5.5

## **Desviación estandar de arrelgo**

In [95]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

## **Obtener la dimension de un arreglo**

In [96]:
np.shape(arreglo)


(10,)

## **Generación de un arreglo de 10 elementos de solo unos**

In [97]:
solo1 = np.ones(10)
solo1


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])