## **Creando una lista de 10 elementoss**

In [183]:
import numpy as np

lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## <h1 style = "color:green"><b> **Transformando de array**<h1>

In [184]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el de tipo de estrucutra**

In [185]:
type(arreglo)


numpy.ndarray

## **Corroborando el tipo de datos de arreglo**

In [186]:
arreglo.dtype


dtype('int32')

## **Definiendo el Array de int32 a float32**

In [187]:
np.array(arreglo, dtype=np.float32)


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32**

In [188]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando los datos de int32 a float32**

In [189]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Tambien existe una función similar en range pero en array**

In [190]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arreglo de 2 en 2 en arange**

In [191]:
arreglonuevo2 = np.arange(1,101,2)
arreglonuevo2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## **Obteniendo le promedio de array**

In [192]:
promedio = np.mean(arreglo)
promedio

5.5

## **Obteniendo mediana de array**

In [193]:
mediana = np.median(arreglo)
mediana

5.5

## **Desviación estandar de arrelgo**

In [194]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

## **Obtener la dimension de un arreglo**

In [195]:
np.shape(arreglo)


(10,)

## **Generación de un arreglo de 10 elementos de solo unos**

In [196]:
solo1 = np.repeat(1,10)
arreglo_de_unos = np.ones(10)
solo1
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **Generación de un arreglo de 10 elementos de solo ceros**

In [197]:
solo0 = np.zeros(10)
solo0   

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## **Transformando el arreglo de unos de punto flotante a enteros**

In [198]:
arreglo_int_ones = arreglo_de_unos.astype(int)  
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## **Generando arreglo aleatorio de 5 elementos**

In [199]:
arrelgo_aleatorio = np.random.rand(5)
arrelgo_aleatorio

array([0.84913516, 0.85417924, 0.4833101 , 0.20951721, 0.36226345])

## **Generando una matriz aleatoria**

In [200]:
matriz = np.random.rand(3,3)
matriz

array([[0.31962263, 0.26785536, 0.07808573],
       [0.58792253, 0.45381189, 0.3684136 ],
       [0.96432731, 0.10351416, 0.50838644]])

## **Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5**

In [201]:
arreglo_aleat2 =np.random.randint(1,100,5)
arreglo_aleat2

array([58, 66, 97, 81,  6])

## **Generando una matriz aleatoria de 10 numeros enteros del 1 al 100**

In [202]:
matriz2 = np.random.randint(10,50(5,5))
matriz2

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\Tkwmn\AppData\Local\Temp\ipykernel_5768\3900321557.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  matriz2 = np.random.randint(10,50(5,5))


TypeError: 'int' object is not callable